### ISSUE TITLE
Drives are not being partitioned with 4k by default

### ISSUE THREAD

**Issue by pkgdemon** [trueos/trueos#62]
@darkfiberiru Reported.  Just adding ticket so we don't forget.  I don't think the text installer has ever had this behavior unlike the graphical installer.

**Comment by kmoore134** [comment]
Yea, I think this was never done on text installer. Question is, do we just want to default to 4k all the time, or do you want some selector available to pick the block-size?

**Comment by miwi-fbsd** [comment]
I personally prefer optional.

**Comment by darkfiberiru** [comment]
I think default to 4k is most sane for zfs. This allows you to be more flexible when growing pool and stops you from stabbing yourself in the foot. Also should give you better performance from 512e(emulated) drives. While only slightly hurting 512n(native) drives with worse small random io. I'm totally for an advanced option to disable this if needed.

I do kinda feel bad saying this with no hard numbers to stand behind. So that might be an argument against doing this until theirs some numbers.

[FreeBSD handbook ZFS](https://www.freebsd.org/doc/handbook/zfs-advanced.html)

> vfs.zfs.min_auto_ashift - Minimum ashift (sector size) that will be used automatically at pool creation time. The value is a power of two. The default value of 9 represents 2^9 = 512, a sector size of 512 bytes. To avoid write amplification and get the best performance, set this value to the largest sector size used by a device in the pool.
Many drives have 4 KB sectors. Using the default ashift of 9 with these drives results in write amplification on these devices. Data that could be contained in a single 4 KB write must instead be written in eight 512-byte writes. ZFS tries to read the native sector size from all devices when creating a pool, but many drives with 4 KB sectors report that their sectors are 512 bytes for compatibility. Setting vfs.zfs.min_auto_ashift to 12 (2^12 = 4096) before creating a pool forces ZFS to use 4 KB blocks for best performance on these drives.
Forcing 4 KB blocks is also useful on pools where disk upgrades are planned. Future disks are likely to use 4 KB sectors, and ashift values cannot be changed after a pool is created.
In some specific cases, the smaller 512-byte block size might be preferable. When used with 512-byte disks for databases, or as storage for virtual machines, less data is transferred during small random reads. This can provide better performance, especially when using a smaller ZFS record size.
